services:
  metagenome:
    image: metagenome
    volumes:
      - gunc:/data/gunc_db
      - gtdbtk-db:/data/gtdbtk_db
gunc-db:
  driver_opts:
    type: none
    device: /data/NHLBI_IDSS/database/gunc_1.0.5db
    o: bind
gtdbtk-db:
  driver_opts:
    type: none
    device: /data/NHLBI_IDSS/database/GTDBtk/release207_v2
    o: bind
kraken1.1-db:
  driver_opts:
    type: none
    device: /fdb/kraken/minikraken_20171019_8GB
    o: bind
kraken2.0-db:
  driver_opts:
    type: none
    device: /fdb/kraken/20210223_standard_8GB_kraken2
    o: bind
bmtagger-index:
  driver_opts:
    type: none
    device: /data/NCBR/apps/genome-assembly/metaWRAP/BMTAGGER_INDEX
    o: bind