name: metawrap_env
channels:
  - defaults
  - conda-forge
  - bioconda
  - ursky
dependencies:
  - python=2.7
  - perl==5.26.2.*
  - blas==2.5 
  - blast==2.6.0 
  - samtools==1.9.*
  - krona==2.7.*
  - kraken==1.1.*
  - biopython=1.68.*
  - bmtagger==3.101.*
  - r-ggplot2==3.1.0.* 
  - r-recommended==3.5.1.* 
  - bioconda::bowtie2==2.3.5.*
  - bioconda::bwa==0.7.17.*
  - bioconda::fastqc==0.11.8.*
  - bioconda::checkm-genome==1.0.12
  - concoct==1.0.0.*
  - r-base==3.5.1
  - bioconda::quast==5.0.2
  - seaborn==0.9.0.*
  - salmon==0.13.1.*
